"""si_v2.safety namespace."""
from .halt_bot_circuit_breaker import (
    HALT_BOT_HALTED,
    HALT_BOT_NORMAL,
    HALT_BOT_REDUCING,
    HALT_BOT_UNKNOWN,
    VALID_HALT_BOT_STATES,
    BotIdValidationError,
    BotSafetyState,
    HaltBotRegistry,
    can_bot_open_new_position,
    clear_bot_halt,
    combine_with_fleet_kill_switch,
    halt_bot,
    is_bot_halted,
    list_halted_bots,
    load_registry_from,
    save_registry_to,
)
from .scoped_freeze import (
    FLEET_PRECEDENCE_ORDER,
    ScopedEntryDecision,
    freeze_all_canonical_bots,
    freeze_bot,
    list_frozen_bots,
    resolve_bot_entry,
    resolve_bot_entry_from_states,
    unfreeze_bot,
)

__all__ = [
    "FLEET_PRECEDENCE_ORDER",
    "HALT_BOT_HALTED",
    "HALT_BOT_NORMAL",
    "HALT_BOT_REDUCING",
    "HALT_BOT_UNKNOWN",
    "VALID_HALT_BOT_STATES",
    "BotIdValidationError",
    "BotSafetyState",
    "HaltBotRegistry",
    "ScopedEntryDecision",
    "can_bot_open_new_position",
    "clear_bot_halt",
    "combine_with_fleet_kill_switch",
    "freeze_all_canonical_bots",
    "freeze_bot",
    "halt_bot",
    "is_bot_halted",
    "list_frozen_bots",
    "list_halted_bots",
    "load_registry_from",
    "resolve_bot_entry",
    "resolve_bot_entry_from_states",
    "save_registry_to",
    "unfreeze_bot",
]
