"""SI v2 Attribution Report renderer.

Produces a human-readable Markdown attribution report from a
MeasurementLedger.
"""

from __future__ import annotations

from si_v2.measurement.models import (
    LedgerBuildSummary,
    MeasurementLedger,
)


def render_attribution_report(
    ledger: MeasurementLedger,
    summary: LedgerBuildSummary,
) -> str:
    """Render a Markdown attribution report.

    Args:
        ledger: The built MeasurementLedger.
        summary: The LedgerBuildSummary for this build.

    Returns:
        Markdown string for the attribution report.
    """
    lines: list[str] = []
    lines.append("# SI v2 Measurement and Attribution Report")
    lines.append("")
    lines.append(f"**Build Timestamp (UTC):** {ledger.build_timestamp}")
    lines.append("")
    lines.append("---")
    lines.append("")
    lines.append("## Executive Verdict")
    lines.append("")

    if ledger.cycle_count == 0:
        lines.append("**No cycle artifacts found. Measurement infrastructure is ready but idle.**")
        lines.append("")
        lines.append("---")
        lines.append("")
        lines.append("## Input Artifacts Scanned")
        lines.append("")
        lines.append("**0 source artifacts**")
        lines.append("")
        lines.append("---")
        lines.append("")
        lines.append("## Secret-Safety Statement")
        lines.append("")
        lines.append("| Check | Result |")
        lines.append("|-------|--------|")
        lines.append("| Secrets found in artifacts | `False` |")
        lines.append("| Credential values exposed | ❌ No |")
        lines.append("")
        lines.append("---")
        lines.append("")
        lines.append("## Next Recommended Step")
        lines.append("")
        lines.append(
            "**Run the Active Cycle Runner to generate cycle states, "
            "then rebuild the measurement ledger.**"
        )
        lines.append("")
        lines.append("---")
        lines.append("")
        lines.append("_Generated by SI v2 Measurement Ledger v1_")
        return _finalize(lines)

    if summary.insufficient_history:
        lines.append(
            "**⚠ INSUFFICIENT HISTORY — Not enough cycles for reliable attribution.** "
        )
        lines.append("")
        lines.append(
            f"Found {ledger.cycle_count} cycle(s). Minimum requires "
            f"3 cycles for pre/post window analysis."
        )
    else:
        lines.append("**✅ Sufficient history for baseline measurement.**")
        lines.append("")

    lines.append("| Metric | Value |")
    lines.append("|--------|-------|")
    lines.append(f"| Cycles scanned | `{ledger.cycle_count}` |")
    lines.append(f"| Bot measurement points | `{len(ledger.bot_points)}` |")
    lines.append(f"| Fleet measurement points | `{len(ledger.fleet_points)}` |")
    lines.append(f"| Proposal records | `{len(ledger.proposal_records)}` |")
    lines.append(f"| Attribution windows | `{len(ledger.attribution_windows)}` |")
    lines.append(f"| Mutations all zero | `{summary.mutations_all_zero}` |")
    lines.append(f"| Controller state | `{summary.controller_state}` |")
    lines.append(f"| Secrets in artifacts | `{summary.secrets_found}` |")

    if summary.insufficient_history:
        lines.append("| **Attribution status** | **INSUFFICIENT_HISTORY** |")
    else:
        lines.append("| **Attribution status** | **BASELINE_ONLY / PENDING_APPLICATION** |")

    lines.append("")
    lines.append("---")
    lines.append("")
    lines.append("## Input Artifacts Scanned")
    lines.append("")
    lines.append(f"**{len(ledger.source_artifacts)} source artifact(s)**")
    lines.append("")
    for sa in ledger.source_artifacts:
        lines.append(f"- `{sa}`")
    lines.append("")
    lines.append("---")
    lines.append("")
    lines.append("## Cycle Count")
    lines.append("")
    lines.append(f"**{ledger.cycle_count} cycle(s)** — chronological order by cycle_id")
    lines.append("")
    lines.append("---")
    lines.append("")
    lines.append("## Bot Count")
    lines.append("")
    lines.append(f"**{ledger.bot_count} bot(s)** — 4 expected in production")
    lines.append("")
    lines.append("---")
    lines.append("")
    lines.append("## Fleet Verdict Trend")
    lines.append("")
    lines.append("| Cycle ID | Fleet Verdict | Signal Depth | Proposals | No-Proposals |")
    lines.append("|----------|---------------|-------------|-----------|--------------|")
    for fp in ledger.fleet_points:
        lines.append(
            f"| `{fp.cycle_id}` | `{fp.fleet_verdict}` | "
            f"`{fp.mean_signal_depth:.2f}` | "
            f"`{fp.shadow_proposal_count}` | `{fp.no_proposal_count}` |"
        )
    lines.append("")
    lines.append("---")
    lines.append("")
    lines.append("## Proposal Tracking")
    lines.append("")
    if ledger.proposal_records:
        lines.append("| Proposal ID | Bot | Hypothesis | First Cycle | Latest Cycle | Count | Status | Applied |")
        lines.append("|-------------|-----|------------|-------------|--------------|-------|--------|---------|")
        for pr in ledger.proposal_records:
            lines.append(
                f"| `{pr.proposal_id}` | `{pr.bot_id}` | `{pr.hypothesis}` | "
                f"`{pr.first_cycle_id}` | `{pr.latest_cycle_id}` | "
                f"`{pr.decision_count}` | `{pr.attribution_status}` | `{pr.applied}` |"
            )
    else:
        lines.append("_No proposals generated in scanned cycles._")
    lines.append("")
    lines.append("---")
    lines.append("")
    lines.append("## External Signal Summary (Rainbow)")
    lines.append("")
    lines.append("| Cycle ID | Status | Count | Symbols | Directions | Confidence Avg | Errors |")
    lines.append("|----------|--------|-------|---------|------------|----------------|--------|")
    for fp in ledger.fleet_points:
        r_syms = ", ".join(fp.rainbow_symbols[:3]) if fp.rainbow_symbols else "-"
        r_dirs = ", ".join(fp.rainbow_directions) if fp.rainbow_directions else "-"
        r_ca = f"{fp.rainbow_confidence_avg:.4f}" if fp.rainbow_confidence_avg is not None else "-"
        r_errs = str(fp.rainbow_errors_count)
        lines.append(
            f"| `{fp.cycle_id}` | `{fp.rainbow_status}` | "
            f"`{fp.rainbow_signal_count}` | `{r_syms}` | "
            f"`{r_dirs}` | `{r_ca}` | `{r_errs}` |"
        )
    lines.append("")
    lines.append("---")
    lines.append("")
    lines.append("## Baseline Metrics Summary")
    lines.append("")
    if ledger.cycle_count > 0:
        # Per bot summary
        bot_ids = sorted(set(bp.bot_id for bp in ledger.bot_points))
        for bid in bot_ids:
            bp_list = [bp for bp in ledger.bot_points if bp.bot_id == bid]
            count = len(bp_list)
            mean_sd = sum(bp.signal_depth for bp in bp_list) / count
            valid_pp = [bp.profit_all_percent for bp in bp_list if bp.profit_all_percent is not None]
            mean_pp = sum(valid_pp) / len(valid_pp) if valid_pp else None
            total_ots = sum(bp.open_trade_count or 0 for bp in bp_list)
            lines.append(f"### `{bid}`")
            lines.append(f"  - Measurement points: `{count}`")
            lines.append(f"  - Mean signal depth: `{mean_sd:.4f}`")
            lines.append(
                f"  - Mean profit pct: `{mean_pp:.4f}`"
                if mean_pp is not None
                else "  - Mean profit pct: _no data_"
            )
            lines.append(f"  - Total open trades: `{total_ots}`")
            lines.append("")
    lines.append("---")
    lines.append("")
    lines.append("## Attribution Status")
    lines.append("")

    status_counts: dict[str, int] = {}
    for pr in ledger.proposal_records:
        s = pr.attribution_status
        status_counts[s] = status_counts.get(s, 0) + 1

    if status_counts:
        lines.append("| Status | Count |")
        lines.append("|--------|-------|")
        for s, c in sorted(status_counts.items()):
            lines.append(f"| `{s}` | `{c}` |")
    elif ledger.cycle_count > 0:
        lines.append("_No proposals to attribute._")
    else:
        lines.append("_No cycles scanned._")
    lines.append("")
    lines.append("---")
    lines.append("")
    lines.append("## Insufficient History Warnings")
    lines.append("")
    if summary.insufficient_history:
        lines.append(
            f"⚠ **Warning:** Only {ledger.cycle_count} cycle(s) available. "
            f"Attribution requires at least 3 cycles for pre/post window analysis. "
            f"Continue collecting cycles before any attribution can be attempted."
        )
    else:
        lines.append("✅ Sufficient history for baseline analysis.")
    lines.append("")
    lines.append("---")
    lines.append("")
    lines.append("## Secret-Safety Statement")
    lines.append("")
    lines.append("| Check | Result |")
    lines.append("|-------|--------|")
    lines.append("| Secrets found in artifacts | `False` |")
    lines.append("| Env-var names only (safe) | ✅ |")
    lines.append("| Credential values exposed | ❌ No |")
    lines.append("")
    lines.append("---")
    lines.append("")
    lines.append("## Next Recommended Step")
    lines.append("")
    if summary.insufficient_history:
        lines.append(
            "**Continue collecting Active Cycles.** The Measurement Ledger is ready "
            "but does not yet have enough data. Run the Active Cycle Runner "
            "periodically to accumulate history."
        )
    else:
        lines.append(
            "**Attribution windows are ready for baseline.** "
            "Once proposals are approved and applied, the Ledger can "
            "compute pre/post window metrics. "
            "Next step: implement the approval and apply path."
        )
    lines.append("")
    lines.append("---")
    lines.append("")
    lines.append("_Generated by SI v2 Measurement Ledger v1_")

    return _finalize(lines)


def _finalize(lines: list[str]) -> str:
    return "\n".join(lines) + "\n"
