#!/usr/bin/env python3
"""
# DEPRECATED 2026-05-21 – forward to trading_pipeline.py
This file is now a thin wrapper. All logic moved to orchestrator/scripts/trading_pipeline.py
as the Single Source of Truth (per Phase 2 Master Plan).

Do not edit this file. Call trading_pipeline.py instead.
RiskGuard, ShadowLogger always-on, and gate policy (0.65/30min) are enforced there.

Run with: python3 orchestrator/scripts/trading_pipeline.py
"""

import subprocess
from pathlib import Path

print("signal_bridge.py is DEPRECATED 2026-05-21. Forwarding to trading_pipeline.py...")
PROJECT_DIR = Path("/home/hermes/projects/trading")
try:
    subprocess.run(
        ["python3", str(PROJECT_DIR / "orchestrator/scripts/trading_pipeline.py")],
        check=True,
        cwd=PROJECT_DIR,
    )
except Exception as e:
    print(f"Forward error: {e}")
    exit(1)
