"""Deterministic renderers for AttributionReport output.

Supports Markdown and JSON output formats.
"""

from __future__ import annotations

import json

from .models import AttributionReport


class MarkdownRenderer:
    """Deterministic Markdown renderer for AttributionReport."""

    def render(self, report: AttributionReport) -> str:
        """Render the report to a Markdown string.

        Args:
            report: The attribution report to render.

        Returns:
            A deterministic Markdown string.
        """
        lines: list[str] = []
        lines.append("# Automated Attribution Report")
        lines.append("")

        # Header metadata
        lines.append("## Report Metadata")
        lines.append("")
        lines.append(f"- **Report ID:** `{report.report_id}`")
        lines.append(f"- **Schema Version:** {report.schema_version}")
        lines.append(f"- **Generated At:** {report.generated_at.isoformat()}")
        if report.period_start:
            lines.append(
                f"- **Period Start:** {report.period_start.isoformat()}"
            )
        if report.period_end:
            lines.append(f"- **Period End:** {report.period_end.isoformat()}")
        if report.source_fingerprint:
            lines.append(
                f"- **Source Fingerprint:** `{report.source_fingerprint[:16]}...`"
            )
        lines.append("")

        # Warnings section (if any)
        if report.warnings:
            lines.append("## Warnings")
            lines.append("")
            for w in report.warnings:
                icon = {
                    "INFO": "[i]",
                    "WARNING": "[!]",
                    "CRITICAL": "[!!]",
                }.get(w.severity, "[i]")
                lines.append(f"- {icon} **[{w.severity}]** {w.message}")
            lines.append("")

        # Sections
        for section in report.sections:
            lines.append(f"## {section.title}")
            lines.append("")
            if section.content:
                lines.append(section.content)
                lines.append("")

        # Footer
        lines.append("---")
        lines.append("")
        lines.append(
            "*Report generated by Automated Attribution Report Builder — "
            "deterministic, read-only, no trading recommendations*"
        )
        lines.append("")

        return "\n".join(lines)


class JSONRenderer:
    """Deterministic JSON renderer for AttributionReport."""

    def render(self, report: AttributionReport) -> str:
        """Render the report to a JSON string.

        Args:
            report: The attribution report to render.

        Returns:
            A deterministic JSON string sorted by keys.
        """
        data = self._to_dict(report)
        return json.dumps(data, indent=2, sort_keys=True, default=str)

    @staticmethod
    def _to_dict(report: AttributionReport) -> dict[str, object]:
        """Convert report to a plain dict for JSON serialization."""
        return {
            "schema_version": report.schema_version,
            "report_id": report.report_id,
            "source_fingerprint": report.source_fingerprint,
            "period_start": (
                report.period_start.isoformat()
                if report.period_start
                else None
            ),
            "period_end": (
                report.period_end.isoformat()
                if report.period_end
                else None
            ),
            "generated_at": report.generated_at.isoformat(),
            "warnings": [
                {
                    "type": w.type.value,
                    "message": w.message,
                    "severity": w.severity.value,
                }
                for w in report.warnings
            ],
            "sections": [
                {
                    "title": s.title,
                    "content": s.content,
                    "data": s.data,
                }
                for s in report.sections
            ],
        }
