"""Attribution Report Renderer.

Reads offline attribution summary output from #111 and renders
a Markdown table by source and regime with sample counts and
confidence buckets.

Missing optional data produces YELLOW-style warnings, not crashes.
"""

from __future__ import annotations

import json
from pathlib import Path


class AttributionReportRenderer:
    """Render an attribution report to Markdown."""

    def __init__(self, root: Path | None = None) -> None:
        self._root = root or Path("self_improvement_v2")

    def _resolve(self, *parts: str) -> Path:
        return self._root.joinpath(*parts)

    def _read_json(self, rel_path: str) -> dict[str, object] | None:
        p = self._resolve(*rel_path.split("/"))
        if not p.exists():
            return None
        try:
            with open(p) as f:
                return dict(json.load(f))
        except (json.JSONDecodeError, OSError):
            return None

    def render(self) -> str:
        """Render a deterministic Markdown attribution report."""
        lines: list[str] = []
        lines.append("# Attribution Report")
        lines.append("")

        attr = self._read_json(
            "reports/attribution/offline_attribution_summary.json"
        )

        if attr is None:
            lines.append("**Status:** degraded")
            lines.append("")
            lines.append(
                "⚠️ Attribution summary not available — "
                "missing or unreadable input file."
            )
            return "\n".join(lines)

        status = str(attr.get("status", "unknown"))
        total = int(attr.get("total_samples", 0))
        win_rate = float(attr.get("overall_win_rate", 0.0))
        src_count = int(attr.get("source_count", 0))

        lines.append(f"**Status:** {status}")
        lines.append(f"**Total Samples:** {total}")
        lines.append(f"**Overall Win Rate:** {win_rate:.1%}")
        lines.append(f"**Source-Regime Combinations:** {src_count}")
        lines.append("")

        rows = attr.get("rows", [])
        if isinstance(rows, list) and rows:
            lines.append(
                "| Source | Regime | Samples | Wins | Losses | "
                "Win Rate | Avg Conf |"
            )
            lines.append(
                "|--------|--------|---------|------|--------|"
                "----------|----------|"
            )
            for r in rows:
                if not isinstance(r, dict):
                    continue
                source_id = str(r.get("source_id", "?"))
                regime = str(r.get("regime_label", "?"))
                samples = int(r.get("sample_count", 0))
                wins = int(r.get("win_count", 0))
                losses = int(r.get("loss_count", 0))
                wr = float(r.get("win_rate", 0.0))
                conf = float(r.get("avg_confidence", 0.0))
                lines.append(
                    f"| {source_id} | {regime} | {samples} | {wins} "
                    f"| {losses} | {wr:.1%} | {conf:.2f} |"
                )

            # Confidence buckets
            lines.append("")
            lines.append("## Confidence Buckets")
            lines.append("")
            high_conf = sum(
                1 for r in rows if isinstance(r, dict) and float(r.get("avg_confidence", 0)) >= 0.8
            )
            mid_conf = sum(
                1 for r in rows if isinstance(r, dict) and 0.6 <= float(r.get("avg_confidence", 0)) < 0.8
            )
            low_conf = sum(
                1 for r in rows if isinstance(r, dict) and float(r.get("avg_confidence", 0)) < 0.6
            )
            lines.append(f"- **High (≥0.80):** {high_conf}")
            lines.append(f"- **Medium (0.60–0.79):** {mid_conf}")
            lines.append(f"- **Low (<0.60):** {low_conf}")
        else:
            lines.append("*No source-regime data available.*")

        # Missing data warnings
        if status != "ok":
            errors = attr.get("errors", [])
            if isinstance(errors, list) and errors:
                lines.append("")
                lines.append("## Warnings")
                lines.append("")
                for err in errors:
                    lines.append(f"- ⚠️ {err}")

        lines.append("")
        lines.append("---")
        lines.append("")
        lines.append(
            "*Report generated by AttributionReportRenderer — "
            "deterministic, offline, no trading recommendations*"
        )

        return "\n".join(lines)
