"""Proposal candidate schema for SI v2 human-review workflow.

Defines the data model for proposal candidates generated by the
self-improvement loop and submitted for human review.
"""

from __future__ import annotations

from dataclasses import dataclass, field
from datetime import UTC, datetime
from enum import StrEnum

JsonScalar = str | int | float | bool | None
JsonValue = JsonScalar | dict[str, "JsonValue"] | list["JsonValue"]
JsonObject = dict[str, JsonValue]


class ProposalDecision(StrEnum):
    """Possible outcomes of the human review process."""

    ACCEPT = "accept"
    REJECT = "reject"
    DEFER = "defer"
    INSUFFICIENT_EVIDENCE = "insufficient_evidence"


class ProposalSource(StrEnum):
    """Origin of the proposal candidate."""

    FLEET_ANALYZER = "fleet_analyzer"
    TELEMETRY_ANALYZER = "telemetry_analyzer"
    ATTRIBUTION_ENGINE = "attribution_engine"
    MANUAL = "manual"


@dataclass
class EvidenceReference:
    """Reference to evidence that supports or contradicts a proposal."""

    category: str
    path: str
    schema_version: int
    summary: str = ""

    def to_json_safe(self) -> JsonObject:
        """Render the evidence reference as a JSON-safe dict."""
        return {
            "category": self.category,
            "path": self.path,
            "schema_version": self.schema_version,
            "summary": self.summary,
        }


@dataclass
class ProposalCandidate:
    """A candidate proposal generated by the SI v2 loop, pending human review.

    The core human-review fields (title, description, rationale, evidence
    references, approval metadata) remain available for the existing
    rendering pipeline. The structured fleet-aware fields added below carry
    the SI-v2 candidate-builder payload used by the evidence bundle and
    future validation workflows.
    """

    proposal_id: str
    source: ProposalSource
    created_at_utc: str = field(
        default_factory=lambda: datetime.now(UTC).strftime("%Y-%m-%dT%H:%M:%SZ")
    )

    # Decision fields
    suggested_decision: ProposalDecision = ProposalDecision.INSUFFICIENT_EVIDENCE
    human_decision: ProposalDecision | None = None
    human_reviewer: str | None = None
    reviewed_at_utc: str | None = None

    # Content
    title: str = ""
    description: str = ""
    rationale: str = ""
    evidence_refs: list[EvidenceReference] = field(default_factory=list)

    # Fleet-aware structured candidate payload
    cycle_id: str = ""
    proposal_type: str = ""
    target_bot_ids: tuple[str, ...] = field(default_factory=tuple)
    hypothesis: str = ""
    candidate_overlay: JsonObject = field(default_factory=dict)
    expected_effect: str = ""
    risk_notes: tuple[str, ...] = field(default_factory=tuple)
    validation_plan: JsonObject = field(default_factory=dict)
    rollback_condition: str = ""
    source_evidence_refs: tuple[str, ...] = field(default_factory=tuple)

    # Metadata
    bot_id: str = ""
    regime_label: str | None = None
    confidence_bucket: str | None = None
    estimated_impact: str = "unknown"  # positive, neutral, negative, unknown

    # Safety
    requires_human_approval: bool = True
    mutation_policy: str = "safe_parameter_overlay_only"
    dry_run_only: bool = True

    @property
    def candidate_id(self) -> str:
        """Alias for the canonical proposal identifier used by the builder."""
        return self.proposal_id

    def to_json_safe(self) -> JsonObject:
        """Render the candidate as a JSON-safe dictionary."""
        return {
            "proposal_id": self.proposal_id,
            "candidate_id": self.candidate_id,
            "source": self.source.value,
            "created_at_utc": self.created_at_utc,
            "suggested_decision": self.suggested_decision.value,
            "human_decision": self.human_decision.value if self.human_decision else None,
            "human_reviewer": self.human_reviewer,
            "reviewed_at_utc": self.reviewed_at_utc,
            "title": self.title,
            "description": self.description,
            "rationale": self.rationale,
            "evidence_refs": [ref.to_json_safe() for ref in self.evidence_refs],
            "cycle_id": self.cycle_id,
            "proposal_type": self.proposal_type,
            "target_bot_ids": list(self.target_bot_ids),
            "hypothesis": self.hypothesis,
            "candidate_overlay": self.candidate_overlay,
            "expected_effect": self.expected_effect,
            "risk_notes": list(self.risk_notes),
            "validation_plan": self.validation_plan,
            "rollback_condition": self.rollback_condition,
            "source_evidence_refs": list(self.source_evidence_refs),
            "bot_id": self.bot_id,
            "regime_label": self.regime_label,
            "confidence_bucket": self.confidence_bucket,
            "estimated_impact": self.estimated_impact,
            "requires_human_approval": self.requires_human_approval,
            "mutation_policy": self.mutation_policy,
            "dry_run_only": self.dry_run_only,
        }
