"""Proposal candidate schema for SI v2 human-review workflow.

Defines the data model for proposal candidates generated by the
self-improvement loop and submitted for human review.
"""

from __future__ import annotations

from dataclasses import dataclass, field
from datetime import UTC, datetime
from enum import StrEnum


class ProposalDecision(StrEnum):
    """Possible outcomes of the human review process."""

    ACCEPT = "accept"
    REJECT = "reject"
    DEFER = "defer"
    INSUFFICIENT_EVIDENCE = "insufficient_evidence"


class ProposalSource(StrEnum):
    """Origin of the proposal candidate."""

    FLEET_ANALYZER = "fleet_analyzer"
    TELEMETRY_ANALYZER = "telemetry_analyzer"
    ATTRIBUTION_ENGINE = "attribution_engine"
    MANUAL = "manual"


@dataclass
class EvidenceReference:
    """Reference to evidence that supports or contradicts a proposal."""

    category: str
    path: str
    schema_version: int
    summary: str


@dataclass
class ProposalCandidate:
    """A candidate proposal generated by the SI v2 loop, pending human review."""

    proposal_id: str
    source: ProposalSource
    created_at_utc: str = field(
        default_factory=lambda: datetime.now(UTC).strftime("%Y-%m-%dT%H:%M:%SZ")
    )

    # Decision fields
    suggested_decision: ProposalDecision = ProposalDecision.INSUFFICIENT_EVIDENCE
    human_decision: ProposalDecision | None = None
    human_reviewer: str | None = None
    reviewed_at_utc: str | None = None

    # Content
    title: str = ""
    description: str = ""
    rationale: str = ""
    evidence_refs: list[EvidenceReference] = field(default_factory=list)

    # Metadata
    bot_id: str = ""
    regime_label: str | None = None
    confidence_bucket: str | None = None
    estimated_impact: str = "unknown"  # positive, neutral, negative, unknown

    # Safety
    requires_human_approval: bool = True
    mutation_policy: str = "safe_parameter_overlay_only"
    dry_run_only: bool = True
